[package]
name = "chatgpt"
version = "0.2.0"
license-file = "LICENSE.md"
edition = "2021"
description = "Markov chain implementation. It's natural langauge generation abilities far surpasses that of any modern LLM (obviously)."

[dependencies]
rand = "0.8.5"
regex = "1.11.0"
